# Generated by Django 5.2.7 on 2026-05-03 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0010_clinicinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='Health_Facility_License',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_doctors', to='MS.clinic'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
